"""empty message

Revision ID: 8e6205c4ed45
Revises: c2b3801e53d5
Create Date: 2024-10-12 21:03:23.501876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e6205c4ed45'
down_revision = 'c2b3801e53d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captcha', sa.String(length=100), nullable=False))
        batch_op.drop_column('catpcha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catpcha', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False))
        batch_op.drop_column('captcha')

    # ### end Alembic commands ###
